### PR TITLE
Update region limits to reflect the new 1.18 world height

### PR DESCRIPTION
**Pull request by janch32**
Some of the players on our server are complaining that they cannot build below Y0 after the new 1.18 update. I briefly looked into the code and found that the minimum and maximum region height values are hard coded to the old world limits. 

I propose to change these values to reflect the new world height limits.

*(moved to uskyblock/uSkyBlock repo as per request https://github.com/rlf/uSkyBlock/pull/1288#issuecomment-1023485736)*

### CODE REVIEW

**Comment by BlackBeltPanda** [comment]
Should probably be using `WorldInfo.getMinHeight()` and `WorldInfo.getMaxHeight()` for world height checks.

**Comment by Muspah** [comment]
Thanks again! Might need to think about a way to update existing regions.

**Comment by janch32** [comment]
> Should probably be using `WorldInfo.getMinHeight()` and `WorldInfo.getMaxHeight()` for world height checks.

Thanks for the suggestion. I updated the code and now it should be more future-proof.



> Thanks again! Might need to think about a way to update existing regions.

No problem! I propose to create new command (something like `/usb wg updateall` or `/usb wg update all`) that will update all island regions. 

Of course this would require the admins to run this command. Maybe the plugin could also check its version number on startup and if the config version is older than this version it could run the command automatically.

**Comment by theleteron** [comment]
It would be a good idea to also check other parts of the code for hardcoded world limits (ex. https://github.com/uskyblock/uSkyBlock/blob/c96543beb006838f2f3b1d220a52402dd05d8f7e/uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/island/level/ChunkSnapshotLevelLogic.java#L80).
For example, everything that is built below or above old limits is not counted towards island level or biome change is not applied below and above old limits.

**Comment by janch32** [comment]
I checked all parts of the source code and (hopefully) fixed every hardcoded world height reference.


**What's fixed:**
- [x] Island region location
- [x] Biomes can now be changed below Y 0
- [x] Score calculation includes blocks outside of range Y 0-255
- [x] Spawn intersection check fixed
- [x] Fixed block limits in island schematic calculation and island regeneration

**Comment by Muspah** [comment]
Thanks very much all, will review and merge when I'm back at the PC with some spare time. Somewhere this week :)

**Comment by janch32** [comment]
The problem with the failing build is because of the outdated reference to FAWE dependency. I have it fixed in my local repository. I can push it if it's not already fixed in another branch.

**Comment by Muspah** [comment]
Feel free to push.

**Comment by Muspah** [comment]
Looks good to me, updating a single region in my test server (/usb wg update) changed the coordinates correctly:

image

Lets merge... Build might fail, there seems to be a new method in OfflinePlayer that we need to expand in our NullPlayer. Will commit afterwards.

**Pull request merged**
