### PR TITLE
FIxing Terraform for netherite tools

### LINKED ISSUE #9: Netherite tools are not working for Terraform
_Please paste the output from `/usb version` below_
```
[15:44:33 INFO]: Name: uSkyBlock
[15:44:33 INFO]: Version: 2.8.9
[15:44:33 INFO]: Description: Ultimate SkyBlock v2.8.9-a693011
[15:44:33 INFO]: Language: cs (cs)
[15:44:33 INFO]:   State: d=256, r=128, i=19, p=24, n=true, awe=false
[15:44:33 INFO]: Server: Paper git-Paper-263 (MC: 1.16.4)
[15:44:33 INFO]:   State: online=false, bungee=false
[15:44:33 INFO]: ------------------------------
[15:44:33 INFO]: Vault 1.7.3-b131 (ENABLED)
[15:44:33 INFO]: WorldEdit 7.3.0-SNAPSHOT+5491-5ae691a (ENABLED)
[15:44:33 INFO]: WorldGuard 7.0.5-SNAPSHOT+2082-d313f2c (ENABLED)
[15:44:33 INFO]: Multiverse-Core 4.2.3-SNAPSHOT-b817 (ENABLED)
[15:44:33 INFO]: Multiverse-NetherPortals 4.2.2-SNAPSHOT-b788 (ENABLED)
[15:44:33 INFO]: ------------------------------
```

_What steps will reproduce the problem?_
1. Configuring netherite tools for terraform

### PR DESCRIPTION
**Pull request by matobodo**
Fixes #9 

I'm not 100% sure if this works, I didn't have time to test it yet, but if I didnt made any typo, everything should be working correctly.

While working on fix for netherite tools, I also added some faling Materials that were aded in newer versions of minecraft. (Red Sand, Concrete Powder)

### CODE REVIEW

**Comment by Muspah** [comment]
Thanks for moving the PR to this repo! Looks good to me, but give me a second to test it out locally. Scaffoldings are falling blocks too, isn't it?

**Comment by matobodo** [comment]
I haven't looked what is the MaterialUtil.SANDS used for. I'll look at it when I arrive home

**Comment by matobodo** [comment]
I just quickly looked into sources and found, that single usage is here:
[NetherTerraFormEvents.java](https://github.com/uskyblock/uSkyBlock/blob/master/uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/event/NetherTerraFormEvents.java#L134) Line 134
We should create new constant for other falling blocks - anvil, scaffolding, ..., and create something like this:
```
private static final Collection<Material> FALLING_BLOCKS= Arrays.asList(Material./*all anvil types*/, Material.SCAFFOLDING, ...); //all blocks that can fall but are not sand related
//Maybe also one arraylist for things like torch, etc.
private static final Collection<Material> FALLING_MATERIALS = new ArrayList<>();

static {
        FALLING_MATERIALS.addAll(SANDS);
        FALLING_MATERIALS.addAll(FALLING_BLOCKS);
    }
```

**Comment by Muspah** [comment]
There seems to be a few more things that need to be changed to make Netherite tools work. At least the default config.yml should be altered to add a tool weight, but it still didn't work on my testserver then. Will get back on it tomorrow or monday, depending on how busy it is over here irl. Not able to do some additional testing right now.

**Comment by matobodo** [comment]
I will have some time finally tonigh for testing.

**Comment by matobodo** [comment]
everything is working on my server, you just need to add NETHERITE in config.yml [2fdbf98](https://github.com/uskyblock/uSkyBlock/pull/10/commits/2fdbf989e5aaefb151fc5ee7da0a11c640d42976)

**Comment by Muspah** [comment]
Not exactly sunday, my apologies... Out of curiosity, what configuration are you using on your server as tool-weight? I'm not sure what the default value should be. 0.2, same as diamond?

**Comment by Muspah** [comment]
Not exactly sunday, my apologies for the delay, but thanks very much for the additional commit. Looks good to me, lets merge.

**Pull request merged**
