### PR TITLE
add challenge "permission" type

### PR DESCRIPTION
**Pull request by Treppenhaus**
Right now this is not completed and needs further testing.

If you dont want this feature in uSkyblock, it's okay. Just close the pull request.
Tell me if I should change something :)
https://github.com/uskyblock/uSkyBlock/issues/28

This adds:
- Challenge.Type.PERMISSION
- String:permission field and getter to `us.talabrek.ultimateskyblock.challenge.Challenge`
- String:permission field and getter to `us.talabrek.ultimateskyblock.challenge.ChallengeDefaults`
- Default value ("usb.challenges.permission-default") to `ChallengeFactory`
- Permission check in ChallengeLogic `tryCompletePermission()`

todo:
- add messag in lang.po file
- edit challenge lore
- add an example to default challenges.yml
- if you decide to accept this, the `permission` option in challenges.yml should be mentioned somehwere, it could be confusing for server owners. (maybe chose another name for it)

### CODE REVIEW

**Comment by Muspah** [comment]
Seems like a reasonable feature request, thanks for the PR. My response time is always horrible, but let me look into it in January :)

**Comment by Muspah** [comment]
If you still want to merge into uSkyblock, feel free to re-open this request with only the related commits. If you want to contribute on a regular basis, we could talk about getting push access.

**Comment by Treppenhaus** [comment]
sorry, I forgot to close this. If its okay, I will open small PRs with small things that could be useful

**Comment by Muspah** [comment]
Absolutely, feel free to!

**Pull request closed without merging**
